language: python
sudo: false
python:
    - "3.5"
    - "3.4"
    - "3.3"
    - "2.7"
    - "2.6"
    # addons:
install:
  - pip install unittest2 mock
  - python setup.py clean --all
  - python setup.py install
script:
  - python -W always setup.py test
