language: python
python:
    - "3.5"
    - "3.4"
    - "3.3"
    - "2.7"
    - "2.6"
install:
    - "pip install flake8"
    - "pip install ."
script:
    - "python -m test.test_wia"
    - "flake8 wia"
    - "flake8 test"
